am_docker_homepage:
    path:     /
    defaults: { _controller: AMDockerBundle:Default:index }
am_docker_container_list:
    path:     /containers
    defaults: { _controller: AMDockerBundle:Container:list }
am_docker_container_listall:
    path:     /containers/all
    defaults: { _controller: AMDockerBundle:Container:listAll }
am_docker_container_add:
    path:     /containers/create
    defaults: { _controller: AMDockerBundle:Container:add }
am_docker_container_details:
    path:     /container/{id}
    defaults: { _controller: AMDockerBundle:Container:details }
am_docker_container_start:
    path:     /container/start/{id}
    defaults: { _controller: AMDockerBundle:Container:start }
am_docker_container_stop:
    path:     /container/stop/{id}
    defaults: { _controller: AMDockerBundle:Container:stop }
am_docker_container_remove:
    path:     /container/remove/{id}
    defaults: { _controller: AMDockerBundle:Container:remove }
am_docker_container_sync:
    path:     /container/sync/{id}
    defaults: { _controller: AMDockerBundle:Container:sync }


am_docker_images:
    path:     /images
    defaults: { _controller: AMDockerBundle:Image:images }
am_docker_images_search:
    path:     /images/search
    defaults: { _controller: AMDockerBundle:Image:search}
am_docker_image_pull:
    path:     /images/pull/{name}
    defaults: { _controller: AMDockerBundle:Image:pull}
    requirements:
        name: "[a-zA-Z0-9_\-\%]+"