am_docker_homepage:
    path:     /
    defaults: { _controller: AMDockerBundle:Default:index }


am_docker_container_list:
    path:     /containers
    defaults: { _controller: AMDockerBundle:Container:list }
am_docker_container_routes:
    resource: "@AMDockerBundle/Resources/config/containers_routing.yml"
    prefix:   /containers


am_docker_usercontainer_list:
    path:     /user-containers
    defaults: { _controller: AMDockerBundle:UserContainer:list }
am_docker_usercontainer_routes:
    resource: "@AMDockerBundle/Resources/config/usercontainer_routing.yml"
    prefix:   /user-containers



am_docker_images:
    path:     /images
    defaults: { _controller: AMDockerBundle:Image:images }
am_docker_images_search:
    path:     /images/search
    defaults: { _controller: AMDockerBundle:Image:search}
