parameters:
    docker_entrypoint: 'unix:///var/run/docker.sock'
    docker_ssl: false
    docker_cert_path: ""

services:
    docker.client:
        class: Docker\DockerClient
        arguments:
            config:
                remote_socket: %docker_entrypoint%
                ssl: %docker_ssl%
                stream_context_options:
                    ssl:
                        cafile: %docker_cert_path%/ca.pem
                        local_cert: %docker_cert_path%/cert.pem
                        local_pk: %docker_cert_path%/key.pem

    docker:
        class: Docker\Docker
        arguments:
            httpClient: @docker.client

