parameters:
    docker_entrypoint: 'unix:///var/run/docker.sock'

services:
    #docker.client:
    #    class: Docker\DockerClient
    #    arguments: []
    docker:
        class: Docker\Docker
        arguments: []
