AM\Bundle\DockerBundle\Entity\Container:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [containerId, name]
            errorPath: containerId
            message: 'This containerId is already in use with that name.'
